---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - nfs-common
  when: nfs_client
  tags:
    - nfs
    - software-installation
    - using-apt

- name: mount
  mount:
    state: mounted
    fstype: nfs
    src: "{{ nfs_client_source }}"
    name: "{{ nfs_client_mount_point }}"
